name: Build Native MHz Tool

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x86 # Windows XP is 32-bit!

      - name: Compile
        run: |
          cl.exe /O2 /GS- /Tc buildfolder/mhz.c /link /subsystem:native,5.01 /entry:NtProcessStartup /NODEFAULTLIB /MACHINE:X86 ntdll.lib /out:mhz.exe
