name: Build Native MHz Tool

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup MSVC
        uses: ilammy/msvc-dev-cmd@v1

      - name: Compile Native Binary
        run: |
          cl.exe /O2 /GS- /Tc buildfolder/mhz.c /link /subsystem:native /entry:NtProcessStartup ntdll.lib /out:mhz.exe

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: mhz-native-binary
          path: mhz.exe
