name: Build Native MHz Tool

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup MSVC (Force x86)
        uses: ilammy/msvc-dev-cmd@v1
        with:
          # This forces the compiler to target 32-bit Windows XP
          arch: x86 

      - name: Compile Native Binary
        run: |
          # /subsystem:native,5.01 -> Targets the XP Native Subsystem
          # /entry:NtProcessStartup -> Sets the correct entry point for ntdll
          # /MACHINE:X86 -> Ensures the header is 32-bit (014C)
          # /NODEFAULTLIB -> Removes dependencies on modern Windows DLLs
          cl.exe /O2 /GS- /Tc mhz.c /link /subsystem:native,5.01 /entry:NtProcessStartup /MACHINE:X86 /NODEFAULTLIB ntdll.lib /out:mhz.exe

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: mhz-native-x86
          path: mhz.exe
